# Here you can find docs bitnami/nginx chart https://github.com/bitnami/charts/blob/main/bitnami/nginx/README.md

image:
  registry: ghcr.io
  repository: tourmalinecore/pelican-cms
  tag: "latest"
  pullPolicy: Always
  debug: true

containerPorts:
  http: 1337
  https: ""

replicaCount: 2

# 1000m means 100% of processor time 
# 1m means 0.1% of processor time.
# at start pod is being allocated with resources from requests, if it needs more consumption can grow until limits.
# if pod uses more resources than limits in spite of the reason kube-system will perform a forced restart
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

updateStrategy:
  # RollingUpdate strategy allows to update service without long downtime
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Here you can read more about container probes https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enabled: true
  path: /cms
  # initialDelaySeconds defines how many seconds after the container is started, the probes start
  initialDelaySeconds: 45
  # periodSeconds defines how long to wait before starting a new probe in case of a failed check.
  periodSeconds: 60

readinessProbe:
  enabled: true
  path: /cms
  initialDelaySeconds: 15
  periodSeconds: 30

service:
  type: ClusterIP
  ports:
    http: 1337
    https: ""

ingress:
  enabled: true
  path: /cms(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: "nginx"
  tls: true


# not needed in this setup
serviceAccount:
  create: false

# not needed in this setup
networkPolicy:
  enabled: false

# CUSTOM: Here you store non secret env vars that will be passed to the pod's environment
extraConfigMapEnvVars:

# this is needed to tell the container to read extra env vars from the dedicated Config Map that we create in extraDeploy
extraEnvVarsCM: "{{ include \"common.names.fullname\" . }}"

podAnnotations:
  # this is needed to trigger re-deploy when only Config Map is changed
  # that is the file name generated by extraDeploy nginx/templates/extra-list.yaml
  # that is why it looks so weird in the file path to calculate hash by its content
  checksum/config: "{{ include (print $.Template.BasePath \"/extra-list.yaml\") . | sha256sum }}"

extraDeploy:
  # this creates Config Map from extraConfigMapEnvVars to be able to calculate checksum/config hash by env vars
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "common.names.fullname" . }}
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" . | nindent 6 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
      {{- end }}
    data:
      {{- if .Values.extraConfigMapEnvVars }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.extraConfigMapEnvVars "context" $ ) | trim | nindent 6 }}
      {{- end }}
